// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: testdata.proto

package pb

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Enum int32

const (
	Enum_ENUM_UNSPECIFIED Enum = 0
	Enum_ENUM_VALUE       Enum = 1
	// Deprecated: Marked as deprecated in testdata.proto.
	Enum_ENUM_DEPRECATED Enum = 2
)

// Enum value maps for Enum.
var (
	Enum_name = map[int32]string{
		0: "ENUM_UNSPECIFIED",
		1: "ENUM_VALUE",
		2: "ENUM_DEPRECATED",
	}
	Enum_value = map[string]int32{
		"ENUM_UNSPECIFIED": 0,
		"ENUM_VALUE":       1,
		"ENUM_DEPRECATED":  2,
	}
)

func (x Enum) Enum() *Enum {
	p := new(Enum)
	*p = x
	return p
}

func (x Enum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Enum) Descriptor() protoreflect.EnumDescriptor {
	return file_testdata_proto_enumTypes[0].Descriptor()
}

func (Enum) Type() protoreflect.EnumType {
	return &file_testdata_proto_enumTypes[0]
}

func (x Enum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Enum.Descriptor instead.
func (Enum) EnumDescriptor() ([]byte, []int) {
	return file_testdata_proto_rawDescGZIP(), []int{0}
}

type AllInclusive struct {
	state                  protoimpl.MessageState        `protogen:"open.v1"`
	Scalar                 int32                         `protobuf:"varint,1,opt,name=scalar,proto3" json:"scalar,omitempty"`
	ScalarOptional         *int32                        `protobuf:"varint,2,opt,name=scalar_optional,json=scalarOptional,proto3,oneof" json:"scalar_optional,omitempty"`
	Timestamp              *timestamp.Timestamp          `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	StringValue            *wrapperspb.StringValue       `protobuf:"bytes,4,opt,name=string_value,json=stringValue,proto3" json:"string_value,omitempty"`
	Enum                   Enum                          `protobuf:"varint,5,opt,name=enum,proto3,enum=Enum" json:"enum,omitempty"`
	OneOf1                 *OneOf                        `protobuf:"bytes,6,opt,name=one_of1,json=oneOf1,proto3" json:"one_of1,omitempty"`
	OneOf2                 *OneOf                        `protobuf:"bytes,12,opt,name=one_of2,json=oneOf2,proto3" json:"one_of2,omitempty"`
	Lists                  *Lists                        `protobuf:"bytes,7,opt,name=lists,proto3" json:"lists,omitempty"`
	Maps                   *Maps                         `protobuf:"bytes,8,opt,name=maps,proto3" json:"maps,omitempty"`
	Message                *Simple                       `protobuf:"bytes,9,opt,name=message,proto3" json:"message,omitempty"`
	MessageRecursive       *AllInclusive                 `protobuf:"bytes,10,opt,name=message_recursive,json=messageRecursive,proto3" json:"message_recursive,omitempty"`
	MessageNestedRecursive *AllInclusive_NestedRecursive `protobuf:"bytes,11,opt,name=message_nested_recursive,json=messageNestedRecursive,proto3" json:"message_nested_recursive,omitempty"`
	// Deprecated: Marked as deprecated in testdata.proto.
	ScalarDeprecated int32 `protobuf:"varint,101,opt,name=scalar_deprecated,json=scalarDeprecated,proto3" json:"scalar_deprecated,omitempty"`
	// Deprecated: Marked as deprecated in testdata.proto.
	ScalarOptionalDeprecated *int32 `protobuf:"varint,102,opt,name=scalar_optional_deprecated,json=scalarOptionalDeprecated,proto3,oneof" json:"scalar_optional_deprecated,omitempty"`
	// Deprecated: Marked as deprecated in testdata.proto.
	TimestampDeprecated *timestamp.Timestamp `protobuf:"bytes,103,opt,name=timestamp_deprecated,json=timestampDeprecated,proto3" json:"timestamp_deprecated,omitempty"`
	// Deprecated: Marked as deprecated in testdata.proto.
	StringValueDeprecated *wrapperspb.StringValue `protobuf:"bytes,104,opt,name=string_value_deprecated,json=stringValueDeprecated,proto3" json:"string_value_deprecated,omitempty"`
	// Deprecated: Marked as deprecated in testdata.proto.
	EnumDeprecated Enum `protobuf:"varint,105,opt,name=enum_deprecated,json=enumDeprecated,proto3,enum=Enum" json:"enum_deprecated,omitempty"`
	// Deprecated: Marked as deprecated in testdata.proto.
	OneOfDeprecated *OneOf `protobuf:"bytes,106,opt,name=one_of_deprecated,json=oneOfDeprecated,proto3" json:"one_of_deprecated,omitempty"`
	// Deprecated: Marked as deprecated in testdata.proto.
	OneOf2Deprecated *OneOf `protobuf:"bytes,112,opt,name=one_of2_deprecated,json=oneOf2Deprecated,proto3" json:"one_of2_deprecated,omitempty"`
	// Deprecated: Marked as deprecated in testdata.proto.
	ListsDeprecated *Lists `protobuf:"bytes,107,opt,name=lists_deprecated,json=listsDeprecated,proto3" json:"lists_deprecated,omitempty"`
	// Deprecated: Marked as deprecated in testdata.proto.
	MapsDeprecated *Maps `protobuf:"bytes,108,opt,name=maps_deprecated,json=mapsDeprecated,proto3" json:"maps_deprecated,omitempty"`
	// Deprecated: Marked as deprecated in testdata.proto.
	MessageDeprecated *Simple `protobuf:"bytes,109,opt,name=message_deprecated,json=messageDeprecated,proto3" json:"message_deprecated,omitempty"`
	// Deprecated: Marked as deprecated in testdata.proto.
	MessageRecursiveDeprecated *AllInclusive `protobuf:"bytes,1010,opt,name=message_recursive_deprecated,json=messageRecursiveDeprecated,proto3" json:"message_recursive_deprecated,omitempty"`
	// Deprecated: Marked as deprecated in testdata.proto.
	MessageNestedRecursiveDeprecated *AllInclusive_NestedRecursive `protobuf:"bytes,1011,opt,name=message_nested_recursive_deprecated,json=messageNestedRecursiveDeprecated,proto3" json:"message_nested_recursive_deprecated,omitempty"`
	unknownFields                    protoimpl.UnknownFields
	sizeCache                        protoimpl.SizeCache
}

func (x *AllInclusive) Reset() {
	*x = AllInclusive{}
	mi := &file_testdata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllInclusive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllInclusive) ProtoMessage() {}

func (x *AllInclusive) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllInclusive.ProtoReflect.Descriptor instead.
func (*AllInclusive) Descriptor() ([]byte, []int) {
	return file_testdata_proto_rawDescGZIP(), []int{0}
}

func (x *AllInclusive) GetScalar() int32 {
	if x != nil {
		return x.Scalar
	}
	return 0
}

func (x *AllInclusive) GetScalarOptional() int32 {
	if x != nil && x.ScalarOptional != nil {
		return *x.ScalarOptional
	}
	return 0
}

func (x *AllInclusive) GetTimestamp() *timestamp.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *AllInclusive) GetStringValue() *wrapperspb.StringValue {
	if x != nil {
		return x.StringValue
	}
	return nil
}

func (x *AllInclusive) GetEnum() Enum {
	if x != nil {
		return x.Enum
	}
	return Enum_ENUM_UNSPECIFIED
}

func (x *AllInclusive) GetOneOf1() *OneOf {
	if x != nil {
		return x.OneOf1
	}
	return nil
}

func (x *AllInclusive) GetOneOf2() *OneOf {
	if x != nil {
		return x.OneOf2
	}
	return nil
}

func (x *AllInclusive) GetLists() *Lists {
	if x != nil {
		return x.Lists
	}
	return nil
}

func (x *AllInclusive) GetMaps() *Maps {
	if x != nil {
		return x.Maps
	}
	return nil
}

func (x *AllInclusive) GetMessage() *Simple {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *AllInclusive) GetMessageRecursive() *AllInclusive {
	if x != nil {
		return x.MessageRecursive
	}
	return nil
}

func (x *AllInclusive) GetMessageNestedRecursive() *AllInclusive_NestedRecursive {
	if x != nil {
		return x.MessageNestedRecursive
	}
	return nil
}

// Deprecated: Marked as deprecated in testdata.proto.
func (x *AllInclusive) GetScalarDeprecated() int32 {
	if x != nil {
		return x.ScalarDeprecated
	}
	return 0
}

// Deprecated: Marked as deprecated in testdata.proto.
func (x *AllInclusive) GetScalarOptionalDeprecated() int32 {
	if x != nil && x.ScalarOptionalDeprecated != nil {
		return *x.ScalarOptionalDeprecated
	}
	return 0
}

// Deprecated: Marked as deprecated in testdata.proto.
func (x *AllInclusive) GetTimestampDeprecated() *timestamp.Timestamp {
	if x != nil {
		return x.TimestampDeprecated
	}
	return nil
}

// Deprecated: Marked as deprecated in testdata.proto.
func (x *AllInclusive) GetStringValueDeprecated() *wrapperspb.StringValue {
	if x != nil {
		return x.StringValueDeprecated
	}
	return nil
}

// Deprecated: Marked as deprecated in testdata.proto.
func (x *AllInclusive) GetEnumDeprecated() Enum {
	if x != nil {
		return x.EnumDeprecated
	}
	return Enum_ENUM_UNSPECIFIED
}

// Deprecated: Marked as deprecated in testdata.proto.
func (x *AllInclusive) GetOneOfDeprecated() *OneOf {
	if x != nil {
		return x.OneOfDeprecated
	}
	return nil
}

// Deprecated: Marked as deprecated in testdata.proto.
func (x *AllInclusive) GetOneOf2Deprecated() *OneOf {
	if x != nil {
		return x.OneOf2Deprecated
	}
	return nil
}

// Deprecated: Marked as deprecated in testdata.proto.
func (x *AllInclusive) GetListsDeprecated() *Lists {
	if x != nil {
		return x.ListsDeprecated
	}
	return nil
}

// Deprecated: Marked as deprecated in testdata.proto.
func (x *AllInclusive) GetMapsDeprecated() *Maps {
	if x != nil {
		return x.MapsDeprecated
	}
	return nil
}

// Deprecated: Marked as deprecated in testdata.proto.
func (x *AllInclusive) GetMessageDeprecated() *Simple {
	if x != nil {
		return x.MessageDeprecated
	}
	return nil
}

// Deprecated: Marked as deprecated in testdata.proto.
func (x *AllInclusive) GetMessageRecursiveDeprecated() *AllInclusive {
	if x != nil {
		return x.MessageRecursiveDeprecated
	}
	return nil
}

// Deprecated: Marked as deprecated in testdata.proto.
func (x *AllInclusive) GetMessageNestedRecursiveDeprecated() *AllInclusive_NestedRecursive {
	if x != nil {
		return x.MessageNestedRecursiveDeprecated
	}
	return nil
}

type OneOf struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to O:
	//
	//	*OneOf_Scalar
	//	*OneOf_Message
	//	*OneOf_ScalarDeprecated
	//	*OneOf_MessageDeprecated
	O             isOneOf_O `protobuf_oneof:"o"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OneOf) Reset() {
	*x = OneOf{}
	mi := &file_testdata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OneOf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneOf) ProtoMessage() {}

func (x *OneOf) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneOf.ProtoReflect.Descriptor instead.
func (*OneOf) Descriptor() ([]byte, []int) {
	return file_testdata_proto_rawDescGZIP(), []int{1}
}

func (x *OneOf) GetO() isOneOf_O {
	if x != nil {
		return x.O
	}
	return nil
}

func (x *OneOf) GetScalar() int32 {
	if x != nil {
		if x, ok := x.O.(*OneOf_Scalar); ok {
			return x.Scalar
		}
	}
	return 0
}

func (x *OneOf) GetMessage() *Simple {
	if x != nil {
		if x, ok := x.O.(*OneOf_Message); ok {
			return x.Message
		}
	}
	return nil
}

// Deprecated: Marked as deprecated in testdata.proto.
func (x *OneOf) GetScalarDeprecated() int32 {
	if x != nil {
		if x, ok := x.O.(*OneOf_ScalarDeprecated); ok {
			return x.ScalarDeprecated
		}
	}
	return 0
}

// Deprecated: Marked as deprecated in testdata.proto.
func (x *OneOf) GetMessageDeprecated() *Simple {
	if x != nil {
		if x, ok := x.O.(*OneOf_MessageDeprecated); ok {
			return x.MessageDeprecated
		}
	}
	return nil
}

type isOneOf_O interface {
	isOneOf_O()
}

type OneOf_Scalar struct {
	Scalar int32 `protobuf:"varint,1,opt,name=scalar,proto3,oneof"`
}

type OneOf_Message struct {
	Message *Simple `protobuf:"bytes,2,opt,name=message,proto3,oneof"`
}

type OneOf_ScalarDeprecated struct {
	// Deprecated: Marked as deprecated in testdata.proto.
	ScalarDeprecated int32 `protobuf:"varint,11,opt,name=scalar_deprecated,json=scalarDeprecated,proto3,oneof"`
}

type OneOf_MessageDeprecated struct {
	// Deprecated: Marked as deprecated in testdata.proto.
	MessageDeprecated *Simple `protobuf:"bytes,12,opt,name=message_deprecated,json=messageDeprecated,proto3,oneof"`
}

func (*OneOf_Scalar) isOneOf_O() {}

func (*OneOf_Message) isOneOf_O() {}

func (*OneOf_ScalarDeprecated) isOneOf_O() {}

func (*OneOf_MessageDeprecated) isOneOf_O() {}

type Lists struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Scalars  []int32                `protobuf:"varint,1,rep,packed,name=scalars,proto3" json:"scalars,omitempty"`
	Messages []*Simple              `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	Enums    []Enum                 `protobuf:"varint,3,rep,packed,name=enums,proto3,enum=Enum" json:"enums,omitempty"`
	// Deprecated: Marked as deprecated in testdata.proto.
	ScalarsDeprecated []int32 `protobuf:"varint,11,rep,packed,name=scalars_deprecated,json=scalarsDeprecated,proto3" json:"scalars_deprecated,omitempty"`
	// Deprecated: Marked as deprecated in testdata.proto.
	MessagesDeprecated []*Simple `protobuf:"bytes,12,rep,name=messages_deprecated,json=messagesDeprecated,proto3" json:"messages_deprecated,omitempty"`
	// Deprecated: Marked as deprecated in testdata.proto.
	EnumsDeprecated []Enum `protobuf:"varint,13,rep,packed,name=enums_deprecated,json=enumsDeprecated,proto3,enum=Enum" json:"enums_deprecated,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Lists) Reset() {
	*x = Lists{}
	mi := &file_testdata_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Lists) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lists) ProtoMessage() {}

func (x *Lists) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lists.ProtoReflect.Descriptor instead.
func (*Lists) Descriptor() ([]byte, []int) {
	return file_testdata_proto_rawDescGZIP(), []int{2}
}

func (x *Lists) GetScalars() []int32 {
	if x != nil {
		return x.Scalars
	}
	return nil
}

func (x *Lists) GetMessages() []*Simple {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *Lists) GetEnums() []Enum {
	if x != nil {
		return x.Enums
	}
	return nil
}

// Deprecated: Marked as deprecated in testdata.proto.
func (x *Lists) GetScalarsDeprecated() []int32 {
	if x != nil {
		return x.ScalarsDeprecated
	}
	return nil
}

// Deprecated: Marked as deprecated in testdata.proto.
func (x *Lists) GetMessagesDeprecated() []*Simple {
	if x != nil {
		return x.MessagesDeprecated
	}
	return nil
}

// Deprecated: Marked as deprecated in testdata.proto.
func (x *Lists) GetEnumsDeprecated() []Enum {
	if x != nil {
		return x.EnumsDeprecated
	}
	return nil
}

type Maps struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Scalars  map[string]string      `protobuf:"bytes,1,rep,name=scalars,proto3" json:"scalars,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Messages map[string]*Simple     `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Enums    map[string]Enum        `protobuf:"bytes,3,rep,name=enums,proto3" json:"enums,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value,enum=Enum"`
	// Deprecated: Marked as deprecated in testdata.proto.
	ScalarsDeprecate map[string]string `protobuf:"bytes,11,rep,name=scalars_deprecate,json=scalarsDeprecate,proto3" json:"scalars_deprecate,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Deprecated: Marked as deprecated in testdata.proto.
	MessagesDeprecate map[string]*Simple `protobuf:"bytes,12,rep,name=messages_deprecate,json=messagesDeprecate,proto3" json:"messages_deprecate,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Deprecated: Marked as deprecated in testdata.proto.
	EnumsDeprecate map[string]Enum `protobuf:"bytes,13,rep,name=enums_deprecate,json=enumsDeprecate,proto3" json:"enums_deprecate,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value,enum=Enum"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Maps) Reset() {
	*x = Maps{}
	mi := &file_testdata_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Maps) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Maps) ProtoMessage() {}

func (x *Maps) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Maps.ProtoReflect.Descriptor instead.
func (*Maps) Descriptor() ([]byte, []int) {
	return file_testdata_proto_rawDescGZIP(), []int{3}
}

func (x *Maps) GetScalars() map[string]string {
	if x != nil {
		return x.Scalars
	}
	return nil
}

func (x *Maps) GetMessages() map[string]*Simple {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *Maps) GetEnums() map[string]Enum {
	if x != nil {
		return x.Enums
	}
	return nil
}

// Deprecated: Marked as deprecated in testdata.proto.
func (x *Maps) GetScalarsDeprecate() map[string]string {
	if x != nil {
		return x.ScalarsDeprecate
	}
	return nil
}

// Deprecated: Marked as deprecated in testdata.proto.
func (x *Maps) GetMessagesDeprecate() map[string]*Simple {
	if x != nil {
		return x.MessagesDeprecate
	}
	return nil
}

// Deprecated: Marked as deprecated in testdata.proto.
func (x *Maps) GetEnumsDeprecate() map[string]Enum {
	if x != nil {
		return x.EnumsDeprecate
	}
	return nil
}

type Simple struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Field int32                  `protobuf:"varint,1,opt,name=field,proto3" json:"field,omitempty"`
	// Deprecated: Marked as deprecated in testdata.proto.
	FieldDeprecated int32 `protobuf:"varint,2,opt,name=field_deprecated,json=fieldDeprecated,proto3" json:"field_deprecated,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Simple) Reset() {
	*x = Simple{}
	mi := &file_testdata_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Simple) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Simple) ProtoMessage() {}

func (x *Simple) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Simple.ProtoReflect.Descriptor instead.
func (*Simple) Descriptor() ([]byte, []int) {
	return file_testdata_proto_rawDescGZIP(), []int{4}
}

func (x *Simple) GetField() int32 {
	if x != nil {
		return x.Field
	}
	return 0
}

// Deprecated: Marked as deprecated in testdata.proto.
func (x *Simple) GetFieldDeprecated() int32 {
	if x != nil {
		return x.FieldDeprecated
	}
	return 0
}

type WithoutDeprecated struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Scalar        int32                     `protobuf:"varint,1,opt,name=scalar,proto3" json:"scalar,omitempty"`
	List          []int32                   `protobuf:"varint,2,rep,packed,name=list,proto3" json:"list,omitempty"`
	Map           map[string]string         `protobuf:"bytes,3,rep,name=map,proto3" json:"map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Message       *WithoutDeprecated_Simple `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithoutDeprecated) Reset() {
	*x = WithoutDeprecated{}
	mi := &file_testdata_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithoutDeprecated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithoutDeprecated) ProtoMessage() {}

func (x *WithoutDeprecated) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithoutDeprecated.ProtoReflect.Descriptor instead.
func (*WithoutDeprecated) Descriptor() ([]byte, []int) {
	return file_testdata_proto_rawDescGZIP(), []int{5}
}

func (x *WithoutDeprecated) GetScalar() int32 {
	if x != nil {
		return x.Scalar
	}
	return 0
}

func (x *WithoutDeprecated) GetList() []int32 {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *WithoutDeprecated) GetMap() map[string]string {
	if x != nil {
		return x.Map
	}
	return nil
}

func (x *WithoutDeprecated) GetMessage() *WithoutDeprecated_Simple {
	if x != nil {
		return x.Message
	}
	return nil
}

type TypesPresence struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Deprecated: Marked as deprecated in testdata.proto.
	Bool bool `protobuf:"varint,1,opt,name=bool,proto3" json:"bool,omitempty"`
	// Deprecated: Marked as deprecated in testdata.proto.
	Float float32 `protobuf:"fixed32,2,opt,name=float,proto3" json:"float,omitempty"`
	// Deprecated: Marked as deprecated in testdata.proto.
	Double float64 `protobuf:"fixed64,3,opt,name=double,proto3" json:"double,omitempty"`
	// Deprecated: Marked as deprecated in testdata.proto.
	Bytes []byte `protobuf:"bytes,4,opt,name=bytes,proto3" json:"bytes,omitempty"`
	// Deprecated: Marked as deprecated in testdata.proto.
	String_ string `protobuf:"bytes,5,opt,name=string,proto3" json:"string,omitempty"`
	// Deprecated: Marked as deprecated in testdata.proto.
	Int32 int32 `protobuf:"varint,7,opt,name=int32,proto3" json:"int32,omitempty"`
	// Deprecated: Marked as deprecated in testdata.proto.
	Int64 int64 `protobuf:"varint,8,opt,name=int64,proto3" json:"int64,omitempty"`
	// Deprecated: Marked as deprecated in testdata.proto.
	Sint32 int32 `protobuf:"zigzag32,9,opt,name=sint32,proto3" json:"sint32,omitempty"`
	// Deprecated: Marked as deprecated in testdata.proto.
	Sint64 int64 `protobuf:"zigzag64,10,opt,name=sint64,proto3" json:"sint64,omitempty"`
	// Deprecated: Marked as deprecated in testdata.proto.
	Sfixed32 int32 `protobuf:"fixed32,11,opt,name=sfixed32,proto3" json:"sfixed32,omitempty"`
	// Deprecated: Marked as deprecated in testdata.proto.
	Sfixed64 int64 `protobuf:"fixed64,12,opt,name=sfixed64,proto3" json:"sfixed64,omitempty"`
	// Deprecated: Marked as deprecated in testdata.proto.
	Uint32 uint32 `protobuf:"varint,13,opt,name=uint32,proto3" json:"uint32,omitempty"`
	// Deprecated: Marked as deprecated in testdata.proto.
	Uint64 uint64 `protobuf:"varint,14,opt,name=uint64,proto3" json:"uint64,omitempty"`
	// Deprecated: Marked as deprecated in testdata.proto.
	Fixed32 uint32 `protobuf:"fixed32,15,opt,name=fixed32,proto3" json:"fixed32,omitempty"`
	// Deprecated: Marked as deprecated in testdata.proto.
	Fixed64 uint64 `protobuf:"fixed64,16,opt,name=fixed64,proto3" json:"fixed64,omitempty"`
	// Deprecated: Marked as deprecated in testdata.proto.
	Enum Enum `protobuf:"varint,6,opt,name=enum,proto3,enum=Enum" json:"enum,omitempty"`
	// Deprecated: Marked as deprecated in testdata.proto.
	OneOf *OneOf `protobuf:"bytes,17,opt,name=one_of,json=oneOf,proto3" json:"one_of,omitempty"`
	// Deprecated: Marked as deprecated in testdata.proto.
	Repeated []int32 `protobuf:"varint,18,rep,packed,name=repeated,proto3" json:"repeated,omitempty"`
	// Deprecated: Marked as deprecated in testdata.proto.
	Map map[string]string `protobuf:"bytes,19,rep,name=map,proto3" json:"map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Deprecated: Marked as deprecated in testdata.proto.
	Message *Simple `protobuf:"bytes,20,opt,name=message,proto3" json:"message,omitempty"`
	// Deprecated: Marked as deprecated in testdata.proto.
	BoolOptional *bool `protobuf:"varint,101,opt,name=bool_optional,json=boolOptional,proto3,oneof" json:"bool_optional,omitempty"`
	// Deprecated: Marked as deprecated in testdata.proto.
	FloatOptional *float32 `protobuf:"fixed32,102,opt,name=float_optional,json=floatOptional,proto3,oneof" json:"float_optional,omitempty"`
	// Deprecated: Marked as deprecated in testdata.proto.
	DoubleOptional *float64 `protobuf:"fixed64,103,opt,name=double_optional,json=doubleOptional,proto3,oneof" json:"double_optional,omitempty"`
	// Deprecated: Marked as deprecated in testdata.proto.
	BytesOptional []byte `protobuf:"bytes,104,opt,name=bytes_optional,json=bytesOptional,proto3,oneof" json:"bytes_optional,omitempty"`
	// Deprecated: Marked as deprecated in testdata.proto.
	StringOptional *string `protobuf:"bytes,105,opt,name=string_optional,json=stringOptional,proto3,oneof" json:"string_optional,omitempty"`
	// Deprecated: Marked as deprecated in testdata.proto.
	Int32Optional *int32 `protobuf:"varint,107,opt,name=int32_optional,json=int32Optional,proto3,oneof" json:"int32_optional,omitempty"`
	// Deprecated: Marked as deprecated in testdata.proto.
	Int64Optional *int64 `protobuf:"varint,108,opt,name=int64_optional,json=int64Optional,proto3,oneof" json:"int64_optional,omitempty"`
	// Deprecated: Marked as deprecated in testdata.proto.
	Sint32Optional *int32 `protobuf:"zigzag32,109,opt,name=sint32_optional,json=sint32Optional,proto3,oneof" json:"sint32_optional,omitempty"`
	// Deprecated: Marked as deprecated in testdata.proto.
	Sint64Optional *int64 `protobuf:"zigzag64,1010,opt,name=sint64_optional,json=sint64Optional,proto3,oneof" json:"sint64_optional,omitempty"`
	// Deprecated: Marked as deprecated in testdata.proto.
	Sfixed32Optional *int32 `protobuf:"fixed32,1011,opt,name=sfixed32_optional,json=sfixed32Optional,proto3,oneof" json:"sfixed32_optional,omitempty"`
	// Deprecated: Marked as deprecated in testdata.proto.
	Sfixed64Optional *int64 `protobuf:"fixed64,1012,opt,name=sfixed64_optional,json=sfixed64Optional,proto3,oneof" json:"sfixed64_optional,omitempty"`
	// Deprecated: Marked as deprecated in testdata.proto.
	Uint32Optional *uint32 `protobuf:"varint,1013,opt,name=uint32_optional,json=uint32Optional,proto3,oneof" json:"uint32_optional,omitempty"`
	// Deprecated: Marked as deprecated in testdata.proto.
	Uint64Optional *uint64 `protobuf:"varint,1014,opt,name=uint64_optional,json=uint64Optional,proto3,oneof" json:"uint64_optional,omitempty"`
	// Deprecated: Marked as deprecated in testdata.proto.
	Fixed32Optional *uint32 `protobuf:"fixed32,1015,opt,name=fixed32_optional,json=fixed32Optional,proto3,oneof" json:"fixed32_optional,omitempty"`
	// Deprecated: Marked as deprecated in testdata.proto.
	Fixed64Optional *uint64 `protobuf:"fixed64,1016,opt,name=fixed64_optional,json=fixed64Optional,proto3,oneof" json:"fixed64_optional,omitempty"`
	// Deprecated: Marked as deprecated in testdata.proto.
	EnumOptional *Enum `protobuf:"varint,106,opt,name=enum_optional,json=enumOptional,proto3,enum=Enum,oneof" json:"enum_optional,omitempty"`
	// Deprecated: Marked as deprecated in testdata.proto.
	OneOfOptional *OneOf `protobuf:"bytes,1017,opt,name=one_of_optional,json=oneOfOptional,proto3,oneof" json:"one_of_optional,omitempty"`
	// Deprecated: Marked as deprecated in testdata.proto.
	MessageOptional *Simple `protobuf:"bytes,1020,opt,name=message_optional,json=messageOptional,proto3,oneof" json:"message_optional,omitempty"`
	// Deprecated: Marked as deprecated in testdata.proto.
	StringValue *wrapperspb.StringValue `protobuf:"bytes,1000,opt,name=string_value,json=stringValue,proto3" json:"string_value,omitempty"`
	// Deprecated: Marked as deprecated in testdata.proto.
	Timestamp *timestamp.Timestamp `protobuf:"bytes,1001,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Deprecated: Marked as deprecated in testdata.proto.
	StringValueOptional *wrapperspb.StringValue `protobuf:"bytes,2000,opt,name=string_value_optional,json=stringValueOptional,proto3,oneof" json:"string_value_optional,omitempty"`
	// Deprecated: Marked as deprecated in testdata.proto.
	TimestampOptional *timestamp.Timestamp `protobuf:"bytes,2001,opt,name=timestamp_optional,json=timestampOptional,proto3,oneof" json:"timestamp_optional,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TypesPresence) Reset() {
	*x = TypesPresence{}
	mi := &file_testdata_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypesPresence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypesPresence) ProtoMessage() {}

func (x *TypesPresence) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypesPresence.ProtoReflect.Descriptor instead.
func (*TypesPresence) Descriptor() ([]byte, []int) {
	return file_testdata_proto_rawDescGZIP(), []int{6}
}

// Deprecated: Marked as deprecated in testdata.proto.
func (x *TypesPresence) GetBool() bool {
	if x != nil {
		return x.Bool
	}
	return false
}

// Deprecated: Marked as deprecated in testdata.proto.
func (x *TypesPresence) GetFloat() float32 {
	if x != nil {
		return x.Float
	}
	return 0
}

// Deprecated: Marked as deprecated in testdata.proto.
func (x *TypesPresence) GetDouble() float64 {
	if x != nil {
		return x.Double
	}
	return 0
}

// Deprecated: Marked as deprecated in testdata.proto.
func (x *TypesPresence) GetBytes() []byte {
	if x != nil {
		return x.Bytes
	}
	return nil
}

// Deprecated: Marked as deprecated in testdata.proto.
func (x *TypesPresence) GetString_() string {
	if x != nil {
		return x.String_
	}
	return ""
}

// Deprecated: Marked as deprecated in testdata.proto.
func (x *TypesPresence) GetInt32() int32 {
	if x != nil {
		return x.Int32
	}
	return 0
}

// Deprecated: Marked as deprecated in testdata.proto.
func (x *TypesPresence) GetInt64() int64 {
	if x != nil {
		return x.Int64
	}
	return 0
}

// Deprecated: Marked as deprecated in testdata.proto.
func (x *TypesPresence) GetSint32() int32 {
	if x != nil {
		return x.Sint32
	}
	return 0
}

// Deprecated: Marked as deprecated in testdata.proto.
func (x *TypesPresence) GetSint64() int64 {
	if x != nil {
		return x.Sint64
	}
	return 0
}

// Deprecated: Marked as deprecated in testdata.proto.
func (x *TypesPresence) GetSfixed32() int32 {
	if x != nil {
		return x.Sfixed32
	}
	return 0
}

// Deprecated: Marked as deprecated in testdata.proto.
func (x *TypesPresence) GetSfixed64() int64 {
	if x != nil {
		return x.Sfixed64
	}
	return 0
}

// Deprecated: Marked as deprecated in testdata.proto.
func (x *TypesPresence) GetUint32() uint32 {
	if x != nil {
		return x.Uint32
	}
	return 0
}

// Deprecated: Marked as deprecated in testdata.proto.
func (x *TypesPresence) GetUint64() uint64 {
	if x != nil {
		return x.Uint64
	}
	return 0
}

// Deprecated: Marked as deprecated in testdata.proto.
func (x *TypesPresence) GetFixed32() uint32 {
	if x != nil {
		return x.Fixed32
	}
	return 0
}

// Deprecated: Marked as deprecated in testdata.proto.
func (x *TypesPresence) GetFixed64() uint64 {
	if x != nil {
		return x.Fixed64
	}
	return 0
}

// Deprecated: Marked as deprecated in testdata.proto.
func (x *TypesPresence) GetEnum() Enum {
	if x != nil {
		return x.Enum
	}
	return Enum_ENUM_UNSPECIFIED
}

// Deprecated: Marked as deprecated in testdata.proto.
func (x *TypesPresence) GetOneOf() *OneOf {
	if x != nil {
		return x.OneOf
	}
	return nil
}

// Deprecated: Marked as deprecated in testdata.proto.
func (x *TypesPresence) GetRepeated() []int32 {
	if x != nil {
		return x.Repeated
	}
	return nil
}

// Deprecated: Marked as deprecated in testdata.proto.
func (x *TypesPresence) GetMap() map[string]string {
	if x != nil {
		return x.Map
	}
	return nil
}

// Deprecated: Marked as deprecated in testdata.proto.
func (x *TypesPresence) GetMessage() *Simple {
	if x != nil {
		return x.Message
	}
	return nil
}

// Deprecated: Marked as deprecated in testdata.proto.
func (x *TypesPresence) GetBoolOptional() bool {
	if x != nil && x.BoolOptional != nil {
		return *x.BoolOptional
	}
	return false
}

// Deprecated: Marked as deprecated in testdata.proto.
func (x *TypesPresence) GetFloatOptional() float32 {
	if x != nil && x.FloatOptional != nil {
		return *x.FloatOptional
	}
	return 0
}

// Deprecated: Marked as deprecated in testdata.proto.
func (x *TypesPresence) GetDoubleOptional() float64 {
	if x != nil && x.DoubleOptional != nil {
		return *x.DoubleOptional
	}
	return 0
}

// Deprecated: Marked as deprecated in testdata.proto.
func (x *TypesPresence) GetBytesOptional() []byte {
	if x != nil {
		return x.BytesOptional
	}
	return nil
}

// Deprecated: Marked as deprecated in testdata.proto.
func (x *TypesPresence) GetStringOptional() string {
	if x != nil && x.StringOptional != nil {
		return *x.StringOptional
	}
	return ""
}

// Deprecated: Marked as deprecated in testdata.proto.
func (x *TypesPresence) GetInt32Optional() int32 {
	if x != nil && x.Int32Optional != nil {
		return *x.Int32Optional
	}
	return 0
}

// Deprecated: Marked as deprecated in testdata.proto.
func (x *TypesPresence) GetInt64Optional() int64 {
	if x != nil && x.Int64Optional != nil {
		return *x.Int64Optional
	}
	return 0
}

// Deprecated: Marked as deprecated in testdata.proto.
func (x *TypesPresence) GetSint32Optional() int32 {
	if x != nil && x.Sint32Optional != nil {
		return *x.Sint32Optional
	}
	return 0
}

// Deprecated: Marked as deprecated in testdata.proto.
func (x *TypesPresence) GetSint64Optional() int64 {
	if x != nil && x.Sint64Optional != nil {
		return *x.Sint64Optional
	}
	return 0
}

// Deprecated: Marked as deprecated in testdata.proto.
func (x *TypesPresence) GetSfixed32Optional() int32 {
	if x != nil && x.Sfixed32Optional != nil {
		return *x.Sfixed32Optional
	}
	return 0
}

// Deprecated: Marked as deprecated in testdata.proto.
func (x *TypesPresence) GetSfixed64Optional() int64 {
	if x != nil && x.Sfixed64Optional != nil {
		return *x.Sfixed64Optional
	}
	return 0
}

// Deprecated: Marked as deprecated in testdata.proto.
func (x *TypesPresence) GetUint32Optional() uint32 {
	if x != nil && x.Uint32Optional != nil {
		return *x.Uint32Optional
	}
	return 0
}

// Deprecated: Marked as deprecated in testdata.proto.
func (x *TypesPresence) GetUint64Optional() uint64 {
	if x != nil && x.Uint64Optional != nil {
		return *x.Uint64Optional
	}
	return 0
}

// Deprecated: Marked as deprecated in testdata.proto.
func (x *TypesPresence) GetFixed32Optional() uint32 {
	if x != nil && x.Fixed32Optional != nil {
		return *x.Fixed32Optional
	}
	return 0
}

// Deprecated: Marked as deprecated in testdata.proto.
func (x *TypesPresence) GetFixed64Optional() uint64 {
	if x != nil && x.Fixed64Optional != nil {
		return *x.Fixed64Optional
	}
	return 0
}

// Deprecated: Marked as deprecated in testdata.proto.
func (x *TypesPresence) GetEnumOptional() Enum {
	if x != nil && x.EnumOptional != nil {
		return *x.EnumOptional
	}
	return Enum_ENUM_UNSPECIFIED
}

// Deprecated: Marked as deprecated in testdata.proto.
func (x *TypesPresence) GetOneOfOptional() *OneOf {
	if x != nil {
		return x.OneOfOptional
	}
	return nil
}

// Deprecated: Marked as deprecated in testdata.proto.
func (x *TypesPresence) GetMessageOptional() *Simple {
	if x != nil {
		return x.MessageOptional
	}
	return nil
}

// Deprecated: Marked as deprecated in testdata.proto.
func (x *TypesPresence) GetStringValue() *wrapperspb.StringValue {
	if x != nil {
		return x.StringValue
	}
	return nil
}

// Deprecated: Marked as deprecated in testdata.proto.
func (x *TypesPresence) GetTimestamp() *timestamp.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// Deprecated: Marked as deprecated in testdata.proto.
func (x *TypesPresence) GetStringValueOptional() *wrapperspb.StringValue {
	if x != nil {
		return x.StringValueOptional
	}
	return nil
}

// Deprecated: Marked as deprecated in testdata.proto.
func (x *TypesPresence) GetTimestampOptional() *timestamp.Timestamp {
	if x != nil {
		return x.TimestampOptional
	}
	return nil
}

type HitMaxDepth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             *HitMaxDepth_A         `protobuf:"bytes,1,opt,name=a,proto3" json:"a,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HitMaxDepth) Reset() {
	*x = HitMaxDepth{}
	mi := &file_testdata_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HitMaxDepth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HitMaxDepth) ProtoMessage() {}

func (x *HitMaxDepth) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HitMaxDepth.ProtoReflect.Descriptor instead.
func (*HitMaxDepth) Descriptor() ([]byte, []int) {
	return file_testdata_proto_rawDescGZIP(), []int{7}
}

func (x *HitMaxDepth) GetA() *HitMaxDepth_A {
	if x != nil {
		return x.A
	}
	return nil
}

type AllInclusive_NestedRecursive struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Message *AllInclusive          `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	// Deprecated: Marked as deprecated in testdata.proto.
	MessageDeprecated *AllInclusive `protobuf:"bytes,2,opt,name=message_deprecated,json=messageDeprecated,proto3" json:"message_deprecated,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AllInclusive_NestedRecursive) Reset() {
	*x = AllInclusive_NestedRecursive{}
	mi := &file_testdata_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllInclusive_NestedRecursive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllInclusive_NestedRecursive) ProtoMessage() {}

func (x *AllInclusive_NestedRecursive) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllInclusive_NestedRecursive.ProtoReflect.Descriptor instead.
func (*AllInclusive_NestedRecursive) Descriptor() ([]byte, []int) {
	return file_testdata_proto_rawDescGZIP(), []int{0, 0}
}

func (x *AllInclusive_NestedRecursive) GetMessage() *AllInclusive {
	if x != nil {
		return x.Message
	}
	return nil
}

// Deprecated: Marked as deprecated in testdata.proto.
func (x *AllInclusive_NestedRecursive) GetMessageDeprecated() *AllInclusive {
	if x != nil {
		return x.MessageDeprecated
	}
	return nil
}

type WithoutDeprecated_Simple struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         int32                  `protobuf:"varint,1,opt,name=field,proto3" json:"field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithoutDeprecated_Simple) Reset() {
	*x = WithoutDeprecated_Simple{}
	mi := &file_testdata_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithoutDeprecated_Simple) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithoutDeprecated_Simple) ProtoMessage() {}

func (x *WithoutDeprecated_Simple) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithoutDeprecated_Simple.ProtoReflect.Descriptor instead.
func (*WithoutDeprecated_Simple) Descriptor() ([]byte, []int) {
	return file_testdata_proto_rawDescGZIP(), []int{5, 0}
}

func (x *WithoutDeprecated_Simple) GetField() int32 {
	if x != nil {
		return x.Field
	}
	return 0
}

type HitMaxDepth_A struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             *HitMaxDepth_X         `protobuf:"bytes,1,opt,name=x,proto3" json:"x,omitempty"`
	B             *HitMaxDepth_B         `protobuf:"bytes,2,opt,name=b,proto3" json:"b,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HitMaxDepth_A) Reset() {
	*x = HitMaxDepth_A{}
	mi := &file_testdata_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HitMaxDepth_A) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HitMaxDepth_A) ProtoMessage() {}

func (x *HitMaxDepth_A) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HitMaxDepth_A.ProtoReflect.Descriptor instead.
func (*HitMaxDepth_A) Descriptor() ([]byte, []int) {
	return file_testdata_proto_rawDescGZIP(), []int{7, 0}
}

func (x *HitMaxDepth_A) GetX() *HitMaxDepth_X {
	if x != nil {
		return x.X
	}
	return nil
}

func (x *HitMaxDepth_A) GetB() *HitMaxDepth_B {
	if x != nil {
		return x.B
	}
	return nil
}

type HitMaxDepth_B struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	C             *HitMaxDepth_C         `protobuf:"bytes,1,opt,name=c,proto3" json:"c,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HitMaxDepth_B) Reset() {
	*x = HitMaxDepth_B{}
	mi := &file_testdata_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HitMaxDepth_B) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HitMaxDepth_B) ProtoMessage() {}

func (x *HitMaxDepth_B) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HitMaxDepth_B.ProtoReflect.Descriptor instead.
func (*HitMaxDepth_B) Descriptor() ([]byte, []int) {
	return file_testdata_proto_rawDescGZIP(), []int{7, 1}
}

func (x *HitMaxDepth_B) GetC() *HitMaxDepth_C {
	if x != nil {
		return x.C
	}
	return nil
}

type HitMaxDepth_C struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	D             *HitMaxDepth_D         `protobuf:"bytes,1,opt,name=d,proto3" json:"d,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HitMaxDepth_C) Reset() {
	*x = HitMaxDepth_C{}
	mi := &file_testdata_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HitMaxDepth_C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HitMaxDepth_C) ProtoMessage() {}

func (x *HitMaxDepth_C) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HitMaxDepth_C.ProtoReflect.Descriptor instead.
func (*HitMaxDepth_C) Descriptor() ([]byte, []int) {
	return file_testdata_proto_rawDescGZIP(), []int{7, 2}
}

func (x *HitMaxDepth_C) GetD() *HitMaxDepth_D {
	if x != nil {
		return x.D
	}
	return nil
}

type HitMaxDepth_D struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	E             *HitMaxDepth_E         `protobuf:"bytes,1,opt,name=e,proto3" json:"e,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HitMaxDepth_D) Reset() {
	*x = HitMaxDepth_D{}
	mi := &file_testdata_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HitMaxDepth_D) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HitMaxDepth_D) ProtoMessage() {}

func (x *HitMaxDepth_D) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HitMaxDepth_D.ProtoReflect.Descriptor instead.
func (*HitMaxDepth_D) Descriptor() ([]byte, []int) {
	return file_testdata_proto_rawDescGZIP(), []int{7, 3}
}

func (x *HitMaxDepth_D) GetE() *HitMaxDepth_E {
	if x != nil {
		return x.E
	}
	return nil
}

type HitMaxDepth_E struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	F             *HitMaxDepth_F         `protobuf:"bytes,1,opt,name=f,proto3" json:"f,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HitMaxDepth_E) Reset() {
	*x = HitMaxDepth_E{}
	mi := &file_testdata_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HitMaxDepth_E) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HitMaxDepth_E) ProtoMessage() {}

func (x *HitMaxDepth_E) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HitMaxDepth_E.ProtoReflect.Descriptor instead.
func (*HitMaxDepth_E) Descriptor() ([]byte, []int) {
	return file_testdata_proto_rawDescGZIP(), []int{7, 4}
}

func (x *HitMaxDepth_E) GetF() *HitMaxDepth_F {
	if x != nil {
		return x.F
	}
	return nil
}

type HitMaxDepth_F struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	G             *HitMaxDepth_G         `protobuf:"bytes,1,opt,name=g,proto3" json:"g,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HitMaxDepth_F) Reset() {
	*x = HitMaxDepth_F{}
	mi := &file_testdata_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HitMaxDepth_F) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HitMaxDepth_F) ProtoMessage() {}

func (x *HitMaxDepth_F) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HitMaxDepth_F.ProtoReflect.Descriptor instead.
func (*HitMaxDepth_F) Descriptor() ([]byte, []int) {
	return file_testdata_proto_rawDescGZIP(), []int{7, 5}
}

func (x *HitMaxDepth_F) GetG() *HitMaxDepth_G {
	if x != nil {
		return x.G
	}
	return nil
}

type HitMaxDepth_G struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	H             *HitMaxDepth_H         `protobuf:"bytes,1,opt,name=h,proto3" json:"h,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HitMaxDepth_G) Reset() {
	*x = HitMaxDepth_G{}
	mi := &file_testdata_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HitMaxDepth_G) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HitMaxDepth_G) ProtoMessage() {}

func (x *HitMaxDepth_G) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HitMaxDepth_G.ProtoReflect.Descriptor instead.
func (*HitMaxDepth_G) Descriptor() ([]byte, []int) {
	return file_testdata_proto_rawDescGZIP(), []int{7, 6}
}

func (x *HitMaxDepth_G) GetH() *HitMaxDepth_H {
	if x != nil {
		return x.H
	}
	return nil
}

type HitMaxDepth_H struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	I             *HitMaxDepth_I         `protobuf:"bytes,1,opt,name=i,proto3" json:"i,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HitMaxDepth_H) Reset() {
	*x = HitMaxDepth_H{}
	mi := &file_testdata_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HitMaxDepth_H) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HitMaxDepth_H) ProtoMessage() {}

func (x *HitMaxDepth_H) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HitMaxDepth_H.ProtoReflect.Descriptor instead.
func (*HitMaxDepth_H) Descriptor() ([]byte, []int) {
	return file_testdata_proto_rawDescGZIP(), []int{7, 7}
}

func (x *HitMaxDepth_H) GetI() *HitMaxDepth_I {
	if x != nil {
		return x.I
	}
	return nil
}

type HitMaxDepth_I struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             *HitMaxDepth_A         `protobuf:"bytes,1,opt,name=a,proto3" json:"a,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HitMaxDepth_I) Reset() {
	*x = HitMaxDepth_I{}
	mi := &file_testdata_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HitMaxDepth_I) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HitMaxDepth_I) ProtoMessage() {}

func (x *HitMaxDepth_I) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HitMaxDepth_I.ProtoReflect.Descriptor instead.
func (*HitMaxDepth_I) Descriptor() ([]byte, []int) {
	return file_testdata_proto_rawDescGZIP(), []int{7, 8}
}

func (x *HitMaxDepth_I) GetA() *HitMaxDepth_A {
	if x != nil {
		return x.A
	}
	return nil
}

type HitMaxDepth_X struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Deprecated: Marked as deprecated in testdata.proto.
	Scalar        int32 `protobuf:"varint,1,opt,name=scalar,proto3" json:"scalar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HitMaxDepth_X) Reset() {
	*x = HitMaxDepth_X{}
	mi := &file_testdata_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HitMaxDepth_X) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HitMaxDepth_X) ProtoMessage() {}

func (x *HitMaxDepth_X) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HitMaxDepth_X.ProtoReflect.Descriptor instead.
func (*HitMaxDepth_X) Descriptor() ([]byte, []int) {
	return file_testdata_proto_rawDescGZIP(), []int{7, 9}
}

// Deprecated: Marked as deprecated in testdata.proto.
func (x *HitMaxDepth_X) GetScalar() int32 {
	if x != nil {
		return x.Scalar
	}
	return 0
}

var File_testdata_proto protoreflect.FileDescriptor

const file_testdata_proto_rawDesc = "" +
	"\n" +
	"\x0etestdata.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\x89\f\n" +
	"\fAllInclusive\x12\x16\n" +
	"\x06scalar\x18\x01 \x01(\x05R\x06scalar\x12,\n" +
	"\x0fscalar_optional\x18\x02 \x01(\x05H\x00R\x0escalarOptional\x88\x01\x01\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12?\n" +
	"\fstring_value\x18\x04 \x01(\v2\x1c.google.protobuf.StringValueR\vstringValue\x12\x19\n" +
	"\x04enum\x18\x05 \x01(\x0e2\x05.EnumR\x04enum\x12\x1f\n" +
	"\aone_of1\x18\x06 \x01(\v2\x06.OneOfR\x06oneOf1\x12\x1f\n" +
	"\aone_of2\x18\f \x01(\v2\x06.OneOfR\x06oneOf2\x12\x1c\n" +
	"\x05lists\x18\a \x01(\v2\x06.ListsR\x05lists\x12\x19\n" +
	"\x04maps\x18\b \x01(\v2\x05.MapsR\x04maps\x12!\n" +
	"\amessage\x18\t \x01(\v2\a.SimpleR\amessage\x12:\n" +
	"\x11message_recursive\x18\n" +
	" \x01(\v2\r.AllInclusiveR\x10messageRecursive\x12W\n" +
	"\x18message_nested_recursive\x18\v \x01(\v2\x1d.AllInclusive.NestedRecursiveR\x16messageNestedRecursive\x12/\n" +
	"\x11scalar_deprecated\x18e \x01(\x05B\x02\x18\x01R\x10scalarDeprecated\x12E\n" +
	"\x1ascalar_optional_deprecated\x18f \x01(\x05B\x02\x18\x01H\x01R\x18scalarOptionalDeprecated\x88\x01\x01\x12Q\n" +
	"\x14timestamp_deprecated\x18g \x01(\v2\x1a.google.protobuf.TimestampB\x02\x18\x01R\x13timestampDeprecated\x12X\n" +
	"\x17string_value_deprecated\x18h \x01(\v2\x1c.google.protobuf.StringValueB\x02\x18\x01R\x15stringValueDeprecated\x122\n" +
	"\x0fenum_deprecated\x18i \x01(\x0e2\x05.EnumB\x02\x18\x01R\x0eenumDeprecated\x126\n" +
	"\x11one_of_deprecated\x18j \x01(\v2\x06.OneOfB\x02\x18\x01R\x0foneOfDeprecated\x128\n" +
	"\x12one_of2_deprecated\x18p \x01(\v2\x06.OneOfB\x02\x18\x01R\x10oneOf2Deprecated\x125\n" +
	"\x10lists_deprecated\x18k \x01(\v2\x06.ListsB\x02\x18\x01R\x0flistsDeprecated\x122\n" +
	"\x0fmaps_deprecated\x18l \x01(\v2\x05.MapsB\x02\x18\x01R\x0emapsDeprecated\x12:\n" +
	"\x12message_deprecated\x18m \x01(\v2\a.SimpleB\x02\x18\x01R\x11messageDeprecated\x12T\n" +
	"\x1cmessage_recursive_deprecated\x18\xf2\a \x01(\v2\r.AllInclusiveB\x02\x18\x01R\x1amessageRecursiveDeprecated\x12q\n" +
	"#message_nested_recursive_deprecated\x18\xf3\a \x01(\v2\x1d.AllInclusive.NestedRecursiveB\x02\x18\x01R messageNestedRecursiveDeprecated\x1a|\n" +
	"\x0fNestedRecursive\x12'\n" +
	"\amessage\x18\x01 \x01(\v2\r.AllInclusiveR\amessage\x12@\n" +
	"\x12message_deprecated\x18\x02 \x01(\v2\r.AllInclusiveB\x02\x18\x01R\x11messageDeprecatedB\x12\n" +
	"\x10_scalar_optionalB\x1d\n" +
	"\x1b_scalar_optional_deprecated\"\xbc\x01\n" +
	"\x05OneOf\x12\x18\n" +
	"\x06scalar\x18\x01 \x01(\x05H\x00R\x06scalar\x12#\n" +
	"\amessage\x18\x02 \x01(\v2\a.SimpleH\x00R\amessage\x121\n" +
	"\x11scalar_deprecated\x18\v \x01(\x05B\x02\x18\x01H\x00R\x10scalarDeprecated\x12<\n" +
	"\x12message_deprecated\x18\f \x01(\v2\a.SimpleB\x02\x18\x01H\x00R\x11messageDeprecatedB\x03\n" +
	"\x01o\"\x8a\x02\n" +
	"\x05Lists\x12\x18\n" +
	"\ascalars\x18\x01 \x03(\x05R\ascalars\x12#\n" +
	"\bmessages\x18\x02 \x03(\v2\a.SimpleR\bmessages\x12\x1b\n" +
	"\x05enums\x18\x03 \x03(\x0e2\x05.EnumR\x05enums\x121\n" +
	"\x12scalars_deprecated\x18\v \x03(\x05B\x02\x18\x01R\x11scalarsDeprecated\x12<\n" +
	"\x13messages_deprecated\x18\f \x03(\v2\a.SimpleB\x02\x18\x01R\x12messagesDeprecated\x124\n" +
	"\x10enums_deprecated\x18\r \x03(\x0e2\x05.EnumB\x02\x18\x01R\x0fenumsDeprecated\"\x95\x06\n" +
	"\x04Maps\x12,\n" +
	"\ascalars\x18\x01 \x03(\v2\x12.Maps.ScalarsEntryR\ascalars\x12/\n" +
	"\bmessages\x18\x02 \x03(\v2\x13.Maps.MessagesEntryR\bmessages\x12&\n" +
	"\x05enums\x18\x03 \x03(\v2\x10.Maps.EnumsEntryR\x05enums\x12L\n" +
	"\x11scalars_deprecate\x18\v \x03(\v2\x1b.Maps.ScalarsDeprecateEntryB\x02\x18\x01R\x10scalarsDeprecate\x12O\n" +
	"\x12messages_deprecate\x18\f \x03(\v2\x1c.Maps.MessagesDeprecateEntryB\x02\x18\x01R\x11messagesDeprecate\x12F\n" +
	"\x0fenums_deprecate\x18\r \x03(\v2\x19.Maps.EnumsDeprecateEntryB\x02\x18\x01R\x0eenumsDeprecate\x1a:\n" +
	"\fScalarsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aD\n" +
	"\rMessagesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1d\n" +
	"\x05value\x18\x02 \x01(\v2\a.SimpleR\x05value:\x028\x01\x1a?\n" +
	"\n" +
	"EnumsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1b\n" +
	"\x05value\x18\x02 \x01(\x0e2\x05.EnumR\x05value:\x028\x01\x1aC\n" +
	"\x15ScalarsDeprecateEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aM\n" +
	"\x16MessagesDeprecateEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1d\n" +
	"\x05value\x18\x02 \x01(\v2\a.SimpleR\x05value:\x028\x01\x1aH\n" +
	"\x13EnumsDeprecateEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1b\n" +
	"\x05value\x18\x02 \x01(\x0e2\x05.EnumR\x05value:\x028\x01\"M\n" +
	"\x06Simple\x12\x14\n" +
	"\x05field\x18\x01 \x01(\x05R\x05field\x12-\n" +
	"\x10field_deprecated\x18\x02 \x01(\x05B\x02\x18\x01R\x0ffieldDeprecated\"\xfb\x01\n" +
	"\x11WithoutDeprecated\x12\x16\n" +
	"\x06scalar\x18\x01 \x01(\x05R\x06scalar\x12\x12\n" +
	"\x04list\x18\x02 \x03(\x05R\x04list\x12-\n" +
	"\x03map\x18\x03 \x03(\v2\x1b.WithoutDeprecated.MapEntryR\x03map\x123\n" +
	"\amessage\x18\x04 \x01(\v2\x19.WithoutDeprecated.SimpleR\amessage\x1a\x1e\n" +
	"\x06Simple\x12\x14\n" +
	"\x05field\x18\x01 \x01(\x05R\x05field\x1a6\n" +
	"\bMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x93\x12\n" +
	"\rTypesPresence\x12\x16\n" +
	"\x04bool\x18\x01 \x01(\bB\x02\x18\x01R\x04bool\x12\x18\n" +
	"\x05float\x18\x02 \x01(\x02B\x02\x18\x01R\x05float\x12\x1a\n" +
	"\x06double\x18\x03 \x01(\x01B\x02\x18\x01R\x06double\x12\x18\n" +
	"\x05bytes\x18\x04 \x01(\fB\x02\x18\x01R\x05bytes\x12\x1a\n" +
	"\x06string\x18\x05 \x01(\tB\x02\x18\x01R\x06string\x12\x18\n" +
	"\x05int32\x18\a \x01(\x05B\x02\x18\x01R\x05int32\x12\x18\n" +
	"\x05int64\x18\b \x01(\x03B\x02\x18\x01R\x05int64\x12\x1a\n" +
	"\x06sint32\x18\t \x01(\x11B\x02\x18\x01R\x06sint32\x12\x1a\n" +
	"\x06sint64\x18\n" +
	" \x01(\x12B\x02\x18\x01R\x06sint64\x12\x1e\n" +
	"\bsfixed32\x18\v \x01(\x0fB\x02\x18\x01R\bsfixed32\x12\x1e\n" +
	"\bsfixed64\x18\f \x01(\x10B\x02\x18\x01R\bsfixed64\x12\x1a\n" +
	"\x06uint32\x18\r \x01(\rB\x02\x18\x01R\x06uint32\x12\x1a\n" +
	"\x06uint64\x18\x0e \x01(\x04B\x02\x18\x01R\x06uint64\x12\x1c\n" +
	"\afixed32\x18\x0f \x01(\aB\x02\x18\x01R\afixed32\x12\x1c\n" +
	"\afixed64\x18\x10 \x01(\x06B\x02\x18\x01R\afixed64\x12\x1d\n" +
	"\x04enum\x18\x06 \x01(\x0e2\x05.EnumB\x02\x18\x01R\x04enum\x12!\n" +
	"\x06one_of\x18\x11 \x01(\v2\x06.OneOfB\x02\x18\x01R\x05oneOf\x12\x1e\n" +
	"\brepeated\x18\x12 \x03(\x05B\x02\x18\x01R\brepeated\x12-\n" +
	"\x03map\x18\x13 \x03(\v2\x17.TypesPresence.MapEntryB\x02\x18\x01R\x03map\x12%\n" +
	"\amessage\x18\x14 \x01(\v2\a.SimpleB\x02\x18\x01R\amessage\x12,\n" +
	"\rbool_optional\x18e \x01(\bB\x02\x18\x01H\x00R\fboolOptional\x88\x01\x01\x12.\n" +
	"\x0efloat_optional\x18f \x01(\x02B\x02\x18\x01H\x01R\rfloatOptional\x88\x01\x01\x120\n" +
	"\x0fdouble_optional\x18g \x01(\x01B\x02\x18\x01H\x02R\x0edoubleOptional\x88\x01\x01\x12.\n" +
	"\x0ebytes_optional\x18h \x01(\fB\x02\x18\x01H\x03R\rbytesOptional\x88\x01\x01\x120\n" +
	"\x0fstring_optional\x18i \x01(\tB\x02\x18\x01H\x04R\x0estringOptional\x88\x01\x01\x12.\n" +
	"\x0eint32_optional\x18k \x01(\x05B\x02\x18\x01H\x05R\rint32Optional\x88\x01\x01\x12.\n" +
	"\x0eint64_optional\x18l \x01(\x03B\x02\x18\x01H\x06R\rint64Optional\x88\x01\x01\x120\n" +
	"\x0fsint32_optional\x18m \x01(\x11B\x02\x18\x01H\aR\x0esint32Optional\x88\x01\x01\x121\n" +
	"\x0fsint64_optional\x18\xf2\a \x01(\x12B\x02\x18\x01H\bR\x0esint64Optional\x88\x01\x01\x125\n" +
	"\x11sfixed32_optional\x18\xf3\a \x01(\x0fB\x02\x18\x01H\tR\x10sfixed32Optional\x88\x01\x01\x125\n" +
	"\x11sfixed64_optional\x18\xf4\a \x01(\x10B\x02\x18\x01H\n" +
	"R\x10sfixed64Optional\x88\x01\x01\x121\n" +
	"\x0fuint32_optional\x18\xf5\a \x01(\rB\x02\x18\x01H\vR\x0euint32Optional\x88\x01\x01\x121\n" +
	"\x0fuint64_optional\x18\xf6\a \x01(\x04B\x02\x18\x01H\fR\x0euint64Optional\x88\x01\x01\x123\n" +
	"\x10fixed32_optional\x18\xf7\a \x01(\aB\x02\x18\x01H\rR\x0ffixed32Optional\x88\x01\x01\x123\n" +
	"\x10fixed64_optional\x18\xf8\a \x01(\x06B\x02\x18\x01H\x0eR\x0ffixed64Optional\x88\x01\x01\x123\n" +
	"\renum_optional\x18j \x01(\x0e2\x05.EnumB\x02\x18\x01H\x0fR\fenumOptional\x88\x01\x01\x128\n" +
	"\x0fone_of_optional\x18\xf9\a \x01(\v2\x06.OneOfB\x02\x18\x01H\x10R\roneOfOptional\x88\x01\x01\x12<\n" +
	"\x10message_optional\x18\xfc\a \x01(\v2\a.SimpleB\x02\x18\x01H\x11R\x0fmessageOptional\x88\x01\x01\x12D\n" +
	"\fstring_value\x18\xe8\a \x01(\v2\x1c.google.protobuf.StringValueB\x02\x18\x01R\vstringValue\x12=\n" +
	"\ttimestamp\x18\xe9\a \x01(\v2\x1a.google.protobuf.TimestampB\x02\x18\x01R\ttimestamp\x12Z\n" +
	"\x15string_value_optional\x18\xd0\x0f \x01(\v2\x1c.google.protobuf.StringValueB\x02\x18\x01H\x12R\x13stringValueOptional\x88\x01\x01\x12S\n" +
	"\x12timestamp_optional\x18\xd1\x0f \x01(\v2\x1a.google.protobuf.TimestampB\x02\x18\x01H\x13R\x11timestampOptional\x88\x01\x01\x1a6\n" +
	"\bMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x10\n" +
	"\x0e_bool_optionalB\x11\n" +
	"\x0f_float_optionalB\x12\n" +
	"\x10_double_optionalB\x11\n" +
	"\x0f_bytes_optionalB\x12\n" +
	"\x10_string_optionalB\x11\n" +
	"\x0f_int32_optionalB\x11\n" +
	"\x0f_int64_optionalB\x12\n" +
	"\x10_sint32_optionalB\x12\n" +
	"\x10_sint64_optionalB\x14\n" +
	"\x12_sfixed32_optionalB\x14\n" +
	"\x12_sfixed64_optionalB\x12\n" +
	"\x10_uint32_optionalB\x12\n" +
	"\x10_uint64_optionalB\x13\n" +
	"\x11_fixed32_optionalB\x13\n" +
	"\x11_fixed64_optionalB\x10\n" +
	"\x0e_enum_optionalB\x12\n" +
	"\x10_one_of_optionalB\x13\n" +
	"\x11_message_optionalB\x18\n" +
	"\x16_string_value_optionalB\x15\n" +
	"\x13_timestamp_optional\"\xa5\x03\n" +
	"\vHitMaxDepth\x12\x1c\n" +
	"\x01a\x18\x01 \x01(\v2\x0e.HitMaxDepth.AR\x01a\x1a?\n" +
	"\x01A\x12\x1c\n" +
	"\x01x\x18\x01 \x01(\v2\x0e.HitMaxDepth.XR\x01x\x12\x1c\n" +
	"\x01b\x18\x02 \x01(\v2\x0e.HitMaxDepth.BR\x01b\x1a!\n" +
	"\x01B\x12\x1c\n" +
	"\x01c\x18\x01 \x01(\v2\x0e.HitMaxDepth.CR\x01c\x1a!\n" +
	"\x01C\x12\x1c\n" +
	"\x01d\x18\x01 \x01(\v2\x0e.HitMaxDepth.DR\x01d\x1a!\n" +
	"\x01D\x12\x1c\n" +
	"\x01e\x18\x01 \x01(\v2\x0e.HitMaxDepth.ER\x01e\x1a!\n" +
	"\x01E\x12\x1c\n" +
	"\x01f\x18\x01 \x01(\v2\x0e.HitMaxDepth.FR\x01f\x1a!\n" +
	"\x01F\x12\x1c\n" +
	"\x01g\x18\x01 \x01(\v2\x0e.HitMaxDepth.GR\x01g\x1a!\n" +
	"\x01G\x12\x1c\n" +
	"\x01h\x18\x01 \x01(\v2\x0e.HitMaxDepth.HR\x01h\x1a!\n" +
	"\x01H\x12\x1c\n" +
	"\x01i\x18\x01 \x01(\v2\x0e.HitMaxDepth.IR\x01i\x1a!\n" +
	"\x01I\x12\x1c\n" +
	"\x01a\x18\x01 \x01(\v2\x0e.HitMaxDepth.AR\x01a\x1a\x1f\n" +
	"\x01X\x12\x1a\n" +
	"\x06scalar\x18\x01 \x01(\x05B\x02\x18\x01R\x06scalar*E\n" +
	"\x04Enum\x12\x14\n" +
	"\x10ENUM_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"ENUM_VALUE\x10\x01\x12\x17\n" +
	"\x0fENUM_DEPRECATED\x10\x02\x1a\x02\b\x01B[B\rTestdataProtoP\x01ZHgithub.com/belo4ya/grpc-api-deprecation/internal/testdata/proto/proto;pbb\x06proto3"

var (
	file_testdata_proto_rawDescOnce sync.Once
	file_testdata_proto_rawDescData []byte
)

func file_testdata_proto_rawDescGZIP() []byte {
	file_testdata_proto_rawDescOnce.Do(func() {
		file_testdata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_testdata_proto_rawDesc), len(file_testdata_proto_rawDesc)))
	})
	return file_testdata_proto_rawDescData
}

var file_testdata_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_testdata_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_testdata_proto_goTypes = []any{
	(Enum)(0),                            // 0: Enum
	(*AllInclusive)(nil),                 // 1: AllInclusive
	(*OneOf)(nil),                        // 2: OneOf
	(*Lists)(nil),                        // 3: Lists
	(*Maps)(nil),                         // 4: Maps
	(*Simple)(nil),                       // 5: Simple
	(*WithoutDeprecated)(nil),            // 6: WithoutDeprecated
	(*TypesPresence)(nil),                // 7: TypesPresence
	(*HitMaxDepth)(nil),                  // 8: HitMaxDepth
	(*AllInclusive_NestedRecursive)(nil), // 9: AllInclusive.NestedRecursive
	nil,                                  // 10: Maps.ScalarsEntry
	nil,                                  // 11: Maps.MessagesEntry
	nil,                                  // 12: Maps.EnumsEntry
	nil,                                  // 13: Maps.ScalarsDeprecateEntry
	nil,                                  // 14: Maps.MessagesDeprecateEntry
	nil,                                  // 15: Maps.EnumsDeprecateEntry
	(*WithoutDeprecated_Simple)(nil),     // 16: WithoutDeprecated.Simple
	nil,                                  // 17: WithoutDeprecated.MapEntry
	nil,                                  // 18: TypesPresence.MapEntry
	(*HitMaxDepth_A)(nil),                // 19: HitMaxDepth.A
	(*HitMaxDepth_B)(nil),                // 20: HitMaxDepth.B
	(*HitMaxDepth_C)(nil),                // 21: HitMaxDepth.C
	(*HitMaxDepth_D)(nil),                // 22: HitMaxDepth.D
	(*HitMaxDepth_E)(nil),                // 23: HitMaxDepth.E
	(*HitMaxDepth_F)(nil),                // 24: HitMaxDepth.F
	(*HitMaxDepth_G)(nil),                // 25: HitMaxDepth.G
	(*HitMaxDepth_H)(nil),                // 26: HitMaxDepth.H
	(*HitMaxDepth_I)(nil),                // 27: HitMaxDepth.I
	(*HitMaxDepth_X)(nil),                // 28: HitMaxDepth.X
	(*timestamp.Timestamp)(nil),          // 29: google.protobuf.Timestamp
	(*wrapperspb.StringValue)(nil),       // 30: google.protobuf.StringValue
}
var file_testdata_proto_depIdxs = []int32{
	29, // 0: AllInclusive.timestamp:type_name -> google.protobuf.Timestamp
	30, // 1: AllInclusive.string_value:type_name -> google.protobuf.StringValue
	0,  // 2: AllInclusive.enum:type_name -> Enum
	2,  // 3: AllInclusive.one_of1:type_name -> OneOf
	2,  // 4: AllInclusive.one_of2:type_name -> OneOf
	3,  // 5: AllInclusive.lists:type_name -> Lists
	4,  // 6: AllInclusive.maps:type_name -> Maps
	5,  // 7: AllInclusive.message:type_name -> Simple
	1,  // 8: AllInclusive.message_recursive:type_name -> AllInclusive
	9,  // 9: AllInclusive.message_nested_recursive:type_name -> AllInclusive.NestedRecursive
	29, // 10: AllInclusive.timestamp_deprecated:type_name -> google.protobuf.Timestamp
	30, // 11: AllInclusive.string_value_deprecated:type_name -> google.protobuf.StringValue
	0,  // 12: AllInclusive.enum_deprecated:type_name -> Enum
	2,  // 13: AllInclusive.one_of_deprecated:type_name -> OneOf
	2,  // 14: AllInclusive.one_of2_deprecated:type_name -> OneOf
	3,  // 15: AllInclusive.lists_deprecated:type_name -> Lists
	4,  // 16: AllInclusive.maps_deprecated:type_name -> Maps
	5,  // 17: AllInclusive.message_deprecated:type_name -> Simple
	1,  // 18: AllInclusive.message_recursive_deprecated:type_name -> AllInclusive
	9,  // 19: AllInclusive.message_nested_recursive_deprecated:type_name -> AllInclusive.NestedRecursive
	5,  // 20: OneOf.message:type_name -> Simple
	5,  // 21: OneOf.message_deprecated:type_name -> Simple
	5,  // 22: Lists.messages:type_name -> Simple
	0,  // 23: Lists.enums:type_name -> Enum
	5,  // 24: Lists.messages_deprecated:type_name -> Simple
	0,  // 25: Lists.enums_deprecated:type_name -> Enum
	10, // 26: Maps.scalars:type_name -> Maps.ScalarsEntry
	11, // 27: Maps.messages:type_name -> Maps.MessagesEntry
	12, // 28: Maps.enums:type_name -> Maps.EnumsEntry
	13, // 29: Maps.scalars_deprecate:type_name -> Maps.ScalarsDeprecateEntry
	14, // 30: Maps.messages_deprecate:type_name -> Maps.MessagesDeprecateEntry
	15, // 31: Maps.enums_deprecate:type_name -> Maps.EnumsDeprecateEntry
	17, // 32: WithoutDeprecated.map:type_name -> WithoutDeprecated.MapEntry
	16, // 33: WithoutDeprecated.message:type_name -> WithoutDeprecated.Simple
	0,  // 34: TypesPresence.enum:type_name -> Enum
	2,  // 35: TypesPresence.one_of:type_name -> OneOf
	18, // 36: TypesPresence.map:type_name -> TypesPresence.MapEntry
	5,  // 37: TypesPresence.message:type_name -> Simple
	0,  // 38: TypesPresence.enum_optional:type_name -> Enum
	2,  // 39: TypesPresence.one_of_optional:type_name -> OneOf
	5,  // 40: TypesPresence.message_optional:type_name -> Simple
	30, // 41: TypesPresence.string_value:type_name -> google.protobuf.StringValue
	29, // 42: TypesPresence.timestamp:type_name -> google.protobuf.Timestamp
	30, // 43: TypesPresence.string_value_optional:type_name -> google.protobuf.StringValue
	29, // 44: TypesPresence.timestamp_optional:type_name -> google.protobuf.Timestamp
	19, // 45: HitMaxDepth.a:type_name -> HitMaxDepth.A
	1,  // 46: AllInclusive.NestedRecursive.message:type_name -> AllInclusive
	1,  // 47: AllInclusive.NestedRecursive.message_deprecated:type_name -> AllInclusive
	5,  // 48: Maps.MessagesEntry.value:type_name -> Simple
	0,  // 49: Maps.EnumsEntry.value:type_name -> Enum
	5,  // 50: Maps.MessagesDeprecateEntry.value:type_name -> Simple
	0,  // 51: Maps.EnumsDeprecateEntry.value:type_name -> Enum
	28, // 52: HitMaxDepth.A.x:type_name -> HitMaxDepth.X
	20, // 53: HitMaxDepth.A.b:type_name -> HitMaxDepth.B
	21, // 54: HitMaxDepth.B.c:type_name -> HitMaxDepth.C
	22, // 55: HitMaxDepth.C.d:type_name -> HitMaxDepth.D
	23, // 56: HitMaxDepth.D.e:type_name -> HitMaxDepth.E
	24, // 57: HitMaxDepth.E.f:type_name -> HitMaxDepth.F
	25, // 58: HitMaxDepth.F.g:type_name -> HitMaxDepth.G
	26, // 59: HitMaxDepth.G.h:type_name -> HitMaxDepth.H
	27, // 60: HitMaxDepth.H.i:type_name -> HitMaxDepth.I
	19, // 61: HitMaxDepth.I.a:type_name -> HitMaxDepth.A
	62, // [62:62] is the sub-list for method output_type
	62, // [62:62] is the sub-list for method input_type
	62, // [62:62] is the sub-list for extension type_name
	62, // [62:62] is the sub-list for extension extendee
	0,  // [0:62] is the sub-list for field type_name
}

func init() { file_testdata_proto_init() }
func file_testdata_proto_init() {
	if File_testdata_proto != nil {
		return
	}
	file_testdata_proto_msgTypes[0].OneofWrappers = []any{}
	file_testdata_proto_msgTypes[1].OneofWrappers = []any{
		(*OneOf_Scalar)(nil),
		(*OneOf_Message)(nil),
		(*OneOf_ScalarDeprecated)(nil),
		(*OneOf_MessageDeprecated)(nil),
	}
	file_testdata_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_testdata_proto_rawDesc), len(file_testdata_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_testdata_proto_goTypes,
		DependencyIndexes: file_testdata_proto_depIdxs,
		EnumInfos:         file_testdata_proto_enumTypes,
		MessageInfos:      file_testdata_proto_msgTypes,
	}.Build()
	File_testdata_proto = out.File
	file_testdata_proto_goTypes = nil
	file_testdata_proto_depIdxs = nil
}
