// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: deprecation.proto

package deprecation

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeprecationDetails struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The date when this method, service, message or field will stop working (format: YYYY-MM-DD).
	EffectiveAt string `protobuf:"bytes,1,opt,name=effective_at,json=effectiveAt,proto3" json:"effective_at,omitempty"`
	// A description to help users understand the reason for deprecation and suggest alternatives.
	Description   string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeprecationDetails) Reset() {
	*x = DeprecationDetails{}
	mi := &file_deprecation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeprecationDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeprecationDetails) ProtoMessage() {}

func (x *DeprecationDetails) ProtoReflect() protoreflect.Message {
	mi := &file_deprecation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeprecationDetails.ProtoReflect.Descriptor instead.
func (*DeprecationDetails) Descriptor() ([]byte, []int) {
	return file_deprecation_proto_rawDescGZIP(), []int{0}
}

func (x *DeprecationDetails) GetEffectiveAt() string {
	if x != nil {
		return x.EffectiveAt
	}
	return ""
}

func (x *DeprecationDetails) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var file_deprecation_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*DeprecationDetails)(nil),
		Field:         1194,
		Name:          "deprecation.service_deprecation_details",
		Tag:           "bytes,1194,opt,name=service_deprecation_details",
		Filename:      "deprecation.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*DeprecationDetails)(nil),
		Field:         1194,
		Name:          "deprecation.method_deprecation_details",
		Tag:           "bytes,1194,opt,name=method_deprecation_details",
		Filename:      "deprecation.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*DeprecationDetails)(nil),
		Field:         1194,
		Name:          "deprecation.message_deprecation_details",
		Tag:           "bytes,1194,opt,name=message_deprecation_details",
		Filename:      "deprecation.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*DeprecationDetails)(nil),
		Field:         1194,
		Name:          "deprecation.field_deprecation_details",
		Tag:           "bytes,1194,opt,name=field_deprecation_details",
		Filename:      "deprecation.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumValueOptions)(nil),
		ExtensionType: (*DeprecationDetails)(nil),
		Field:         1194,
		Name:          "deprecation.enum_value_deprecation_details",
		Tag:           "bytes,1194,opt,name=enum_value_deprecation_details",
		Filename:      "deprecation.proto",
	},
}

// Extension fields to descriptorpb.ServiceOptions.
var (
	// Contains additional information about the planned deprecation of a service.
	// Used along with `option deprecated = true`.
	//
	// optional deprecation.DeprecationDetails service_deprecation_details = 1194;
	E_ServiceDeprecationDetails = &file_deprecation_proto_extTypes[0]
)

// Extension fields to descriptorpb.MethodOptions.
var (
	// Contains additional information about the planned deprecation of a method.
	// Used along with `option deprecated = true`.
	//
	// optional deprecation.DeprecationDetails method_deprecation_details = 1194;
	E_MethodDeprecationDetails = &file_deprecation_proto_extTypes[1]
)

// Extension fields to descriptorpb.MessageOptions.
var (
	// Contains additional information about the planned deprecation of a message.
	// Used along with `option deprecated = true`.
	//
	// optional deprecation.DeprecationDetails message_deprecation_details = 1194;
	E_MessageDeprecationDetails = &file_deprecation_proto_extTypes[2]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// Contains additional information about the planned deprecation of a field.
	// Used along with `[deprecated = true]`.
	//
	// optional deprecation.DeprecationDetails field_deprecation_details = 1194;
	E_FieldDeprecationDetails = &file_deprecation_proto_extTypes[3]
)

// Extension fields to descriptorpb.EnumValueOptions.
var (
	// Contains additional information about the planned deprecation of enum value.
	// Used along with `[deprecated = true]`.
	//
	// optional deprecation.DeprecationDetails enum_value_deprecation_details = 1194;
	E_EnumValueDeprecationDetails = &file_deprecation_proto_extTypes[4]
)

var File_deprecation_proto protoreflect.FileDescriptor

const file_deprecation_proto_rawDesc = "" +
	"\n" +
	"\x11deprecation.proto\x12\vdeprecation\x1a google/protobuf/descriptor.proto\"Y\n" +
	"\x12DeprecationDetails\x12!\n" +
	"\feffective_at\x18\x01 \x01(\tR\veffectiveAt\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription:\x81\x01\n" +
	"\x1bservice_deprecation_details\x12\x1f.google.protobuf.ServiceOptions\x18\xaa\t \x01(\v2\x1f.deprecation.DeprecationDetailsR\x19serviceDeprecationDetails:~\n" +
	"\x1amethod_deprecation_details\x12\x1e.google.protobuf.MethodOptions\x18\xaa\t \x01(\v2\x1f.deprecation.DeprecationDetailsR\x18methodDeprecationDetails:\x81\x01\n" +
	"\x1bmessage_deprecation_details\x12\x1f.google.protobuf.MessageOptions\x18\xaa\t \x01(\v2\x1f.deprecation.DeprecationDetailsR\x19messageDeprecationDetails:{\n" +
	"\x19field_deprecation_details\x12\x1d.google.protobuf.FieldOptions\x18\xaa\t \x01(\v2\x1f.deprecation.DeprecationDetailsR\x17fieldDeprecationDetails:\x88\x01\n" +
	"\x1eenum_value_deprecation_details\x12!.google.protobuf.EnumValueOptions\x18\xaa\t \x01(\v2\x1f.deprecation.DeprecationDetailsR\x1benumValueDeprecationDetailsB\xa4\x01\n" +
	"\x0fcom.deprecationB\x10DeprecationProtoP\x01Z3github.com/belo4ya/grpc-api-deprecation/deprecation\xa2\x02\x03DXX\xaa\x02\vDeprecation\xca\x02\vDeprecation\xe2\x02\x17Deprecation\\GPBMetadata\xea\x02\vDeprecationb\x06proto3"

var (
	file_deprecation_proto_rawDescOnce sync.Once
	file_deprecation_proto_rawDescData []byte
)

func file_deprecation_proto_rawDescGZIP() []byte {
	file_deprecation_proto_rawDescOnce.Do(func() {
		file_deprecation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_deprecation_proto_rawDesc), len(file_deprecation_proto_rawDesc)))
	})
	return file_deprecation_proto_rawDescData
}

var file_deprecation_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_deprecation_proto_goTypes = []any{
	(*DeprecationDetails)(nil),            // 0: deprecation.DeprecationDetails
	(*descriptorpb.ServiceOptions)(nil),   // 1: google.protobuf.ServiceOptions
	(*descriptorpb.MethodOptions)(nil),    // 2: google.protobuf.MethodOptions
	(*descriptorpb.MessageOptions)(nil),   // 3: google.protobuf.MessageOptions
	(*descriptorpb.FieldOptions)(nil),     // 4: google.protobuf.FieldOptions
	(*descriptorpb.EnumValueOptions)(nil), // 5: google.protobuf.EnumValueOptions
}
var file_deprecation_proto_depIdxs = []int32{
	1,  // 0: deprecation.service_deprecation_details:extendee -> google.protobuf.ServiceOptions
	2,  // 1: deprecation.method_deprecation_details:extendee -> google.protobuf.MethodOptions
	3,  // 2: deprecation.message_deprecation_details:extendee -> google.protobuf.MessageOptions
	4,  // 3: deprecation.field_deprecation_details:extendee -> google.protobuf.FieldOptions
	5,  // 4: deprecation.enum_value_deprecation_details:extendee -> google.protobuf.EnumValueOptions
	0,  // 5: deprecation.service_deprecation_details:type_name -> deprecation.DeprecationDetails
	0,  // 6: deprecation.method_deprecation_details:type_name -> deprecation.DeprecationDetails
	0,  // 7: deprecation.message_deprecation_details:type_name -> deprecation.DeprecationDetails
	0,  // 8: deprecation.field_deprecation_details:type_name -> deprecation.DeprecationDetails
	0,  // 9: deprecation.enum_value_deprecation_details:type_name -> deprecation.DeprecationDetails
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	5,  // [5:10] is the sub-list for extension type_name
	0,  // [0:5] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_deprecation_proto_init() }
func file_deprecation_proto_init() {
	if File_deprecation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_deprecation_proto_rawDesc), len(file_deprecation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 5,
			NumServices:   0,
		},
		GoTypes:           file_deprecation_proto_goTypes,
		DependencyIndexes: file_deprecation_proto_depIdxs,
		MessageInfos:      file_deprecation_proto_msgTypes,
		ExtensionInfos:    file_deprecation_proto_extTypes,
	}.Build()
	File_deprecation_proto = out.File
	file_deprecation_proto_goTypes = nil
	file_deprecation_proto_depIdxs = nil
}
